/* m.c */
int main(int argc, char *argv[]);
int others(void);
char *chcopy(char *p, char *q);
char *writem(int *pp);
char *symnam(int i);
int summary(void);
int setunion(register *a, register *b);
int prlook(struct looksets *p);
int cpres(void);
int cpfir(void);
int state(int c);
int putitem(int *ptr, struct looksets *lptr);
int cempty(void);
int stagen(void);
int closure(int i);
struct looksets *flset(struct looksets *p);
int setup(int argc, char *argv[]);
int finact(void);
int defin(int t, register char *s);
int defout(void);
char *cstash(register char *s);
int gettok(void);
int fdtype(int t);
int chfind(int t, register char *s);
int cpyunion(void);
int cpycode(void);
int skipcom(void);
int cpyact(int offset);
int lhsfill(char *s);
int rhsfill(char *s);
int lrprnt(void);
int beg_debug(void);
int end_toks(void);
int end_debug(void);
int output(void);
int go2out(void);
int go2gen(int c);
int precftn(int r, int t, int s);
int wract(int i);
int wrstate(int i);
int warray(char *s, int *v, int n);
int hideprod(void);
int callopt(void);
int gin(int i);
int stin(int i);
int nxti(void);
int osummary(void);
int aoutput(void);
int arout(char *s, int *v, int n);
int gtnm(void);
