/* m.c */
int main(int argc,const char *argv[]);
void others(void);
char *chcopy(char *p, const char *q);
const char *writem(int *pp);
const char *symnam(int i);
void summary(void);
void aryfil(int *v, int n, int c);
int setunion(int *a, int *b);
void prlook(struct looksets *p);
void cpres(void);
void cpfir(void);
int state(int c);
void putitem(int *ptr, struct looksets *lptr);
void cempty(void);
void stagen(void);
void closure(int i);
struct looksets *flset(struct looksets *p);
void setup(int argc, const char* argv[]);
void finact(void);
int defin(int t, const char *s);
void defout(void);
const char *cstash(const char *s);
int gettok(void);
int fdtype(int t);
int chfind(int t, const char *s);
void cpyunion(void);
void cpycode(void);
int skipcom(void);
void cpyact(int offset);
void lhsfill(const char *s);
void rhsfill(const char *s);
void lrprnt(void);
void beg_debug(void);
void end_toks(void);
void end_debug(void);
void output(void);
int apack(int *p, int n);
void go2out(void);
void go2gen(int c);
void precftn(int r, int t, int s);
void wract(int i);
void wrstate(int i);
void wdef(const char *s, int n);
void warray(const char *s, int *v, int n);
void hideprod(void);
void callopt(void);
void gin(int i);
void stin(int i);
int nxti(void);
void osummary(void);
void aoutput(void);
void arout(const char *s, int *v, int n);
int gtnm(void);
